# Generated by Django 4.1.7 on 2023-03-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="topic", name="owner",),
    ]
